Raoke10086/Raoke10086.Admin/Models/ProductViewModels.cs
using Raoke10086.Infrastructure.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Raoke10086.Admin.Models
{

}

Raoke10086/Raoke10086.Admin/Controllers/ProductController.cs
using Raoke10086.Service.Abstracts;
using Raoke10086.Service.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Raoke10086.Admin.Extensions;

namespace Raoke10086.Admin.Controllers
{
    [RoutePrefix("product")]
    public class ProductController : Controller
    {
        private readonly IToolkitSvc _toolkitSvc;
        private readonly IProductSvc _productSvc;


        public ProductController(IToolkitSvc toolkitSvc,IProductSvc productSvc)
        {
            _toolkitSvc = toolkitSvc;
            _productSvc = productSvc;
        }

        [HttpGet,Route("")]
        public ActionResult Index(ProductFilterOfPage model)
        {
            ViewBag.Categories = _productSvc.GetCategory(Guid.Parse("39F77A79-8290-459C-A9DB-3AE808DC8A07"));
            ViewBag.AllCities = _productSvc.GetAllCity(Current.LCID);
            return View(_productSvc.Get(User.Identity.GetUserID(), model));
        }

        [HttpGet,Route("editor/{id}"),Route("editor")]
        public ActionResult Editor(Guid? id)
        {
            ViewBag.Id = id;
            ViewBag.QiniuToken = _toolkitSvc.GetQiniuToken("image");
            ViewBag.Categories = _productSvc.GetCategory(Guid.Parse("39F77A79-8290-459C-A9DB-3AE808DC8A07"));
            ViewBag.AllCities = _productSvc.GetAllCity(Current.LCID);
            if(id.HasValue)
            {
                var product = _productSvc.Get(User.Identity.GetUserID(), id.Value);
                return View(new UpdateProductDto
                {
                    CategaryID = product.CategaryID,
                    City = product.City,
                    Cover = product.Cover,
                    Details = product.Details,
                    Galleries = product.Galleries,
                    Introduction = product.Introduction,
                    IsVirtual = product.IsVirtual,
                    Messages = product.Messages,
                    NoteMessage = product.NoteMessage,
                    OriginPrice = product.OriginPrice,
                    PostPrice = product.PostPrice,
                    SalePrice = product.SalePrice,
                    ServiceProvider = product.ServiceProvider,
                    Stock = product.Stock,
                    Tags = product.Tags,
                    Title = product.Title
                });
            }
            return View();
        }

        [HttpPost, Route("editor/{id}"), Route("editor")]
        public ActionResult Editor(Guid? id, UpdateProductDto model)
        {
            _productSvc.Update(User.Identity.GetUserID(), id, model);
            return RedirectToAction("Index");
        }
    }
}

Raoke10086/Raoke10086.Admin/Views/Product/Editor.cshtml
@using Raoke10086.Infrastructure.Extensions
@using Raoke10086.Service.Models
@using Raoke10086.Infrastructure.Enums
@model UpdateProductDto
@{
    ViewBag.Title = "Editor";
    PageData["PageID"] = "Product.Index";
    var AllCitySelectListItems = (ViewBag.AllCities as List<CityInListDto>).Select(x => new SelectListItem() { Value = x.Code, Text = x.Name });
    var CategorySelectListItems = (ViewBag.Categories as List<CategoryInListDto>).Select(x => new SelectListItem() { Value = x.ID.ToString(), Text = x.Name });
    var ServiceProviderSelectListItems = typeof(ServiceProvider).ToArrayList().ToArray().Select(x => {
        var item = (KeyValuePair<Enum, string>)x ;
        return new SelectListItem() { Value=item.Key.ToString(),Text=item.Value };
    });
}

@section styles{
    @Styles.Render("~/Content/simditor")
    }
@section scripts{
    @Scripts.Render("~/bundles/simditor")
    <script type="text/javascript">
        /*图片删除控件*/
        $(document).on("click", '.image-container .controls .remove', function (e) {
            var control = $(this);
            bootbox.confirm({
                title: "提醒",
                message: "Are you sure?",
                locale: "zh_CN",
                callback: function (result) {
                    if (result) {
                        control.parents('.image-container').remove();
                    }
                }
            });
        });
        $(document).ready(function () {
            var $preview, editor, mobileToolbar, toolbar;
            Simditor.locale = 'zh-CN';
            toolbar = ['title', 'bold', 'italic', 'underline', 'strikethrough', 'fontScale', 'color', '|', 'ol', 'ul', 'blockquote', 'code', 'table', '|', 'link', 'image', 'hr', '|', 'indent', 'outdent', 'alignment'];
            window.editor = new Simditor({
                textarea: $('#editor'),
                toolbar: toolbar,
                pasteImage: true,
                upload: {
                    domain: 'http://o6ss4fdk1.bkt.clouddn.com',
                    token: '@ViewBag.QiniuToken',
                    url: 'http://upload.qiniu.com',
                    fileKey: "file",
                    connectionCount: 3,
                    leaveConfirm: 'Uploading is in progres...'
                },
            });
        })

        /*图片上传*/
        var uploader = simple.uploader({
            domain: 'http://o6ss4fdk1.bkt.clouddn.com',
            token: '@ViewBag.QiniuToken',
            url: 'http://upload.qiniu.com',
            fileKey: "file",
            connectionCount: 3,
            leaveConfirm: 'Uploading is in progres...'
        });

        $('#select-file').on('change', function (e) {
            uploader.upload(this.files);
        });
        uploader.on('uploadsuccess', function (e, file, result) {
            addImage(result['file_path']);
        });
        function addImage(url) {
            $('.add-image').before('<div class="image-container">'
                                             + '<div class="controls">'
                                                  + '<a class="control-btn move"> <i class="fa fa-arrows"></i> </a>'
                                                  + '<a class="control-btn remove"><i class="fa fa-trash-o"></i> </a>'
                                             + '</div>'
                                             + '<div class="image" data-url="' + url + '" style="background-image:url(\'' + url + '\')"></div>'
                                  + '</div>');
        }

    </script>
}
<input type="file" id="select-file" style="display:none" />
<article class="content item-editor-page">
    <div class="title-block">
        <h3 class="title">
            发布商品 <span class="sparkline bar" data-type="bar"></span>
        </h3>
    </div>
    @using (Html.BeginForm("Editor", "Product", new { @id = ViewBag.Id }, FormMethod.Post, new { @id = "product-editor-form" }))
    {
        <div class="card card-default">
            <div class="card-header">
                <div class="header-block">
                    <p class="title"> 基本信息 </p>
                </div>
            </div>
            <div class="card card-block">
                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        类目:
                    </label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(m => m.CategaryID, CategorySelectListItems, new { @class = "c-select form-control boxed" })
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        标题:
                    </label>
                    <div class="col-sm-10"> @Html.TextBoxFor(m => m.Title, new { @class = "form-control underlined", @placeholder = "限30字内" }) </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        商品类型:
                    </label>
                    <div class="col-sm-10">
                        <label>
                            @Html.RadioButtonFor(m => m.IsVirtual, false, new { @class = "radio squared", @checked = "checked" })
                            <span>实物商品</span>
                        </label>
                        <label>
                            @Html.RadioButtonFor(m => m.IsVirtual, true, new { @class = "radio squared" })
                            <span>虚拟商品</span>
                        </label>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        提供商:
                    </label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(m => m.ServiceProvider, ServiceProviderSelectListItems, new { @class = "c-select form-control boxed" })
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        发货城市:
                    </label>
                    <div class="col-sm-10">
                        @Html.DropDownListFor(m => m.City, AllCitySelectListItems, new { @class = "c-select form-control boxed" })
                    </div>
                </div>
            </div>
        </div>
        <div class="card card-default">
            <div class="card-header">
                <div class="header-block">
                    <p class="title"> 库存/售价 </p>
                </div>
            </div>
            <div class="card card-block">
                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        售价:
                    </label>
                    <div class="col-sm-2 input-group">
                        @Html.TextBoxFor(m => m.SalePrice, new { @class = "form-control underlined", @placeholder = "需低于原价" })
                        <span class="input-group-addon">元</span>
                    </div>

                    <label class="col-sm-1 form-control-label text-xs-right">
                        原价:
                    </label>
                    <div class="col-sm-2 input-group">
                        @Html.TextBoxFor(m => m.OriginPrice, new { @class = "form-control underlined", @placeholder = "" })
                        <span class="input-group-addon">元</span>
                    </div>
                </div>
               
                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        邮费:
                    </label>
                    <div class="col-sm-2 input-group">@Html.TextBoxFor(m => m.PostPrice, new { @class = "form-control underlined", @placeholder = "邮费为0元时显示包邮" })<span class="input-group-addon">元</span></div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        库存:
                    </label>
                    <div class="col-sm-2"> @Html.TextBoxFor(m => m.Stock, new { @class = "form-control underlined", @placeholder = "发布后商品同步更新" }) </div>
                </div>
            </div>
        </div>

        <div class="card card-default">
            <div class="card-header">
                <div class="header-block">
                    <p class="title"> 商品详情 </p>
                </div>
            </div>
            <div class="card card-block">
                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        图片:
                    </label>
                    <div class="col-sm-11">
                        <div class="images-container">
                            @foreach (var image in (Model?.Galleries)??new string[0])
                            {
                                <div class="image-container">
                                    <div class="controls">
                                        <a class="control-btn move"><i class="fa fa-arrows"></i> </a>
                                        <a class="control-btn remove"><i class="fa fa-trash-o"></i> </a>
                                    </div>
                                    <div class="image" data-url="@image" style="background-image:url('@image')"></div>
                                </div>
                            }

                            <a href="#" class="add-image" onclick="$('#select-file').click();">
                                <div class="image-container new">
                                    <div class="image"> <i class="fa fa-plus"></i> </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>



                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        简介:
                    </label>
                    <div class="col-sm-10">@Html.TextAreaFor(m => m.Introduction, new { @class = "form-control", @placeholder = "微信分享给好友时会显示这里的文案" })</div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-1 form-control-label text-xs-right">
                        详情:
                    </label>
                    <div class="col-sm-10">
                        <textarea id="editor" placeholder="商品详情" autofocus>
                            @(Model?.Details)
                        </textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-12 col-sm-offset-1">
                        <button type="submit" class="btn btn-primary">
                            确定
                        </button>
                    </div>
                </div>
            </div>
        </div>
    }
</article>

Raoke10086/Raoke10086.Admin/Views/Product/Index.cshtml
@using Raoke10086.Service.Models
@using Raoke10086.Admin.Extensions
@using Raoke10086.Infrastructure.Enums
@model PageList<ProductInListDto>

@{
    ViewBag.Title = "商品库";
    PageData["PageID"] = "Product.Index";
    var AllCitySelectListItems = (ViewBag.AllCities as List<CityInListDto>);
    var CategorySelectListItems = (ViewBag.Categories as List<CategoryInListDto>);
}
@section scripts{
    <script type="text/javascript">
        /*商品删除控件*/
        $(document).on("click", '.item-actions-list .remove', function (e) {
            var control = $(this);
            bootbox.confirm({
                title: "删除提醒",
                message: "Are you sure?",
                locale: "zh_CN",
                callback: function (result) {
                    if (result) {
                        var item = control.parents('.item');
                        $.ajax({
                            url: "/api/product/" + item.data("id"),
                            method:"DELETE",
                            success:function(){
                                item.remove();
                            }
                        });
                    }
                }
            });
        });

        $(document).on("click", '.item-actions-list .listing:not(.active)', function (e) {
            var control = $(this);
            bootbox.confirm({
                title: "上架提醒",
                message: "Are you sure?",
                locale: "zh_CN",
                callback: function (result) {
                    if (result) {
                        var item = control.parents('.item');
                        $.ajax({
                            url: "/api/product/" + item.data("id") + "/listing",
                            method: "PUT",
                            success: function () {
                                control.addClass("active");
                                item.find(".delisting").removeClass("active");
                            }
                        });
                    }
                }
            });
        });

        $(document).on("click", '.item-actions-list .delisting:not(.active)', function (e) {
            var control = $(this);
            bootbox.confirm({
                title: "下架提醒",
                message: "Are you sure?",
                locale: "zh_CN",
                callback: function (result) {
                    if (result) {
                        var item = control.parents('.item');
                        $.ajax({
                            url: "/api/product/" + item.data("id") + "/delisting",
                            method: "PUT",
                            success: function () {
                                control.addClass("active");
                                item.find(".listing").removeClass("active");
                            }
                        });
                    }
                }
            });
        });
     </script>
}

<article class="content items-list-page">
    <div class="title-search-block">
        <div class="title-block">
            <div class="row">
                <div class="col-md-6">
                    <h3 class="title">
                        商品库
                        <a href="@Url.Action("editor")" class="btn btn-primary btn-sm rounded-s">
                            添加商品
                        </a>

                        @*<div class="action dropdown">
                            <button class="btn  btn-sm rounded-s btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                批量操作
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <a class="dropdown-item" href="#"><i class="fa fa-pencil-square-o icon"></i>上架</a>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#confirm-modal"><i class="fa fa-close icon"></i>下架</a>
                            </div>
                        </div>*@


                    </h3>
                    <p class="title-description">  </p>
                </div>
            </div>
        </div>
        <div class="items-search">
            @using (Html.BeginForm("Index", "Product", FormMethod.Get, new { @class = "form-inline" }))
            {
                <div class="input-group">
                    @Html.TextBox("Keywords",null,new { @class= "form-control boxed rounded-s", @placeholder="搜索商品" })
                    <span class="input-group-btn">
                        <button class="btn btn-secondary rounded-s" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            }
        </div>
    </div>

    @*<div>
        <div class="action dropdown">
            <button class="btn  btn-sm rounded-s btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                商品分类
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                @foreach (var item in CategorySelectListItems)
                {
                    <a class="dropdown-item" href="#">@item.Name</a>
                }
            </div>
        </div>

        <div class="action dropdown">
            <button class="btn  btn-sm rounded-s btn-secondary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                商品分类
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                @foreach (var item in CategorySelectListItems)
                {
                    <a class="dropdown-item" href="#">@item.Name</a>
                }
            </div>
        </div>
    </div>*@



    <div class="card items">
        <ul class="item-list striped">
            <li class="item item-list-header hidden-sm-down">
                <div class="item-row">
                    <div class="item-col fixed item-col-check">
                        <label class="item-check" id="select-all-items">
                            <input type="checkbox" class="checkbox">
                            <span></span>
                        </label>
                    </div>
                    <div class="item-col item-col-header fixed item-col-img md">
                        <div> <span></span> </div>
                    </div>
                    <div class="item-col item-col-header item-col-title">
                        <div> <span>商品</span> </div>
                    </div>
                    <div class="item-col item-col-header item-col-sales">
                        <div> <span>库存/销售量</span> </div>
                    </div>
                    <div class="item-col item-col-header item-col-category">
                        <div class="no-overflow"> <span>分类</span> </div>
                    </div>
                    <div class="item-col item-col-header item-col-author">
                        <div class="no-overflow"> <span>售价</span> </div>
                    </div>
                    <div class="item-col item-col-header fixed item-col-actions-dropdown"> </div>
                </div>
            </li>
            @foreach (var item in Model.Data)
            {
                <li class="item" data-id="@item.ID">
                    <div class="item-row">
                        <div class="item-col fixed item-col-check">
                            <label class="item-check" id="select-all-items">
                                <input type="checkbox" class="checkbox">
                                <span></span>
                            </label>
                        </div>
                        <div class="item-col fixed item-col-img md">
                            <a target="_blank" href="@("http://wx.raoke10086.com/shop/detail/" + item.ID.ToString("N"))">
                                <div class="item-img rounded" style="background-image: url(@item.Cover)"></div>
                            </a>
                        </div>
                        <div class="item-col fixed pull-left item-col-title">
                            <div class="item-heading">商品</div>
                            <div>
                                <a target="_blank" href="@("http://wx.raoke10086.com/shop/detail/" + item.ID.ToString("N"))">
                                    <h4 class="item-title">
                                        @item.Title
                                    </h4>
                                </a>
                            </div>
                        </div>
                        <div class="item-col item-col-sales">
                            <div class="item-heading">库存/销售量</div>
                            <div> @string.Format("{0}/{1}", item.Stock, item.Sold) </div>
                        </div>
                        <div class="item-col item-col-category no-overflow">
                            <div class="item-heading">分类</div>
                            <div class="no-overflow"> <a href="">@item.CategoryName</a> </div>
                        </div>
                        <div class="item-col item-col-author">
                            <div class="item-heading">售价</div>
                            <div class="no-overflow">@item.SalePrice</div>
                        </div>

                        <div class="item-col fixed item-col-actions-dropdown">
                            <div class="item-actions-dropdown">
                                <a class="item-actions-toggle-btn">
                                    <span class="inactive">
                                        <i class="fa fa-cog"></i>
                                    </span> <span class="active">
                                        <i class="fa fa-chevron-circle-right"></i>
                                    </span>
                                </a>
                                <div class="item-actions-block">
                                    <ul class="item-actions-list">
                                        <li>
                                            <a class="remove"> <i class="fa fa-trash-o "></i> </a>
                                        </li>

                                        <li>
                                            <a class="edit" href="@Url.Action("Editor", new { id = item.ID })"> <i class="fa fa-pencil"></i> </a>
                                        </li>

                                        <li>
                                            <a class="listing@((item.State==ProductState.OnSale)?" active":string.Empty)"> <i class="fa fa-chevron-circle-up"></i> </a>
                                        </li>

                                        <li>
                                            <a class="delisting@((item.State==ProductState.SoldOut || item.State==ProductState.Unpublished)?" active":string.Empty)"> <i class="fa fa-chevron-circle-down"></i> </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                }
        </ul>
    </div>
    <nav class="text-xs-right">
        @Html.Pager(Model, Request.Url)
    </nav>
</article>